#!/usr/bin/env python3
"""Fetch, lock, verify, and activate the site's local Lora webfonts.

The deployed site should use committed local font files, not live Google Fonts
requests. The first run downloads the same Google Fonts CSS request used by the
original design, rewrites the WOFF2 URLs to local files, and records a manifest
with SHA-256 hashes. Later `make fonts` runs verify the committed files and
rewrite HTML links without contacting Google again.

To deliberately refresh from Google, run `make refresh-fonts`. If the upstream
CSS or font binaries change, the new hashes will be recorded in the manifest so
the change is explicit in version control rather than silent at deploy time.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "fonts" / "lora"
FONT_CSS = ROOT / "css" / "local-fonts.css"
MANIFEST = FONT_DIR / "MANIFEST.json"
SOURCE = FONT_DIR / "SOURCE.txt"
GOOGLE_CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Lora:ital,wght@0,400..700;1,400..700&display=block"
)
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/149.0.0.0 Safari/537.36"
)

URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")
GOOGLE_LINK_RE = re.compile(
    r'\n?<link[^>]+(?:fonts\.googleapis\.com|fonts\.gstatic\.com)[^>]*>',
    flags=re.IGNORECASE,
)
LOCAL_FONT_LINK_RE = re.compile(r'\n?<link[^>]+data-local-font(?:s)?="lora"[^>]*>', re.IGNORECASE)
LOCAL_LINK_MARKER = '<link href="{path}" rel="stylesheet" data-local-fonts="lora"/>'
PRELOAD_MARKER = (
    '<link href="{path}" rel="preload" as="font" type="font/woff2" crossorigin data-local-font="lora"/>'
)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def rel_from_html(html_path: Path, target: Path) -> str:
    rel = target.relative_to(ROOT)
    if html_path.parent == ROOT:
        return rel.as_posix()
    return (Path("..") / rel).as_posix()


def html_files() -> list[Path]:
    return [ROOT / "index.html", *sorted((ROOT / "pages").glob("*.html"))]


def remove_old_generated_fonts() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for path in FONT_DIR.glob("lora-google-*.woff2"):
        path.unlink()


def download_and_rewrite_css() -> dict:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    css_bytes = fetch(GOOGLE_CSS_URL)
    css = css_bytes.decode("utf-8")
    fonts: list[dict[str, object]] = []

    def replace_url(match: re.Match[str]) -> str:
        url = match.group(1)
        data = fetch(url)
        digest = sha256_bytes(data)
        basename = Path(urlparse(url).path).name or "lora.woff2"
        filename = f"lora-google-{digest[:12]}-{basename}"
        target = FONT_DIR / filename
        target.write_bytes(data)
        fonts.append({
            "file": f"fonts/lora/{filename}",
            "sha256": digest,
            "bytes": len(data),
            "source_url": url,
        })
        return f"url('../fonts/lora/{filename}')"

    rewritten_css = URL_RE.sub(replace_url, css)
    if not fonts:
        raise SystemExit("Google Fonts CSS was fetched, but no fonts.gstatic.com URLs were found.")

    banner = (
        "/* Generated by scripts/fetch_fonts.py. Do not hand-edit.\n"
        "   Source: the original Google Fonts CSS request for Lora. */\n"
    )
    rewritten_css = banner + rewritten_css
    FONT_CSS.write_text(rewritten_css, encoding="utf-8")

    manifest = {
        "source_css_url": GOOGLE_CSS_URL,
        "user_agent": USER_AGENT,
        "source_css_sha256": sha256_bytes(css_bytes),
        "generated_css": "css/local-fonts.css",
        "generated_css_sha256": sha256_file(FONT_CSS),
        "fonts": fonts,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    SOURCE.write_text(
        "Local Lora fonts generated by make fonts / make refresh-fonts.\n"
        f"CSS source: {GOOGLE_CSS_URL}\n"
        f"User-Agent: {USER_AGENT}\n"
        "Locked hashes are recorded in fonts/lora/MANIFEST.json.\n",
        encoding="utf-8",
    )
    return manifest


def load_manifest() -> dict:
    if not MANIFEST.exists():
        raise SystemExit("No font manifest found. Run `make fonts` once to generate local font assets.")
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def verify_manifest(manifest: dict) -> None:
    css_rel = manifest.get("generated_css")
    if css_rel != "css/local-fonts.css":
        raise SystemExit("Unexpected generated_css in font manifest.")
    if not FONT_CSS.exists():
        raise SystemExit("css/local-fonts.css is missing. Run `make refresh-fonts` to regenerate it.")
    expected_css_hash = manifest.get("generated_css_sha256")
    if expected_css_hash and sha256_file(FONT_CSS) != expected_css_hash:
        raise SystemExit("css/local-fonts.css does not match fonts/lora/MANIFEST.json.")

    for item in manifest.get("fonts", []):
        rel = item.get("file")
        expected_hash = item.get("sha256")
        if not isinstance(rel, str) or not isinstance(expected_hash, str):
            raise SystemExit("Malformed font entry in fonts/lora/MANIFEST.json.")
        path = ROOT / rel
        if not path.exists():
            raise SystemExit(f"Missing font file: {rel}")
        if sha256_file(path) != expected_hash:
            raise SystemExit(f"Font file hash mismatch: {rel}")


def preload_fonts_from_css(manifest: dict) -> list[Path]:
    css = FONT_CSS.read_text(encoding="utf-8")
    fonts = [ROOT / item["file"] for item in manifest.get("fonts", [])]
    chosen: list[Path] = []

    for style in ("normal", "italic"):
        for font_path in fonts:
            name = re.escape(font_path.name)
            block_re = re.compile(
                r"@font-face\s*{[^}]*font-style:\s*" + style +
                r";[^}]*" + name + r"[^}]*unicode-range:\s*[^;}]*U\+0000-00FF",
                flags=re.IGNORECASE | re.DOTALL,
            )
            if block_re.search(css):
                chosen.append(font_path)
                break

    return chosen or fonts[:2]


def activate_local_fonts(manifest: dict) -> None:
    preload_paths = preload_fonts_from_css(manifest)
    for html_path in html_files():
        html = html_path.read_text(encoding="utf-8")
        html = GOOGLE_LINK_RE.sub("", html)
        html = LOCAL_FONT_LINK_RE.sub("", html)

        local_links = [
            PRELOAD_MARKER.format(path=rel_from_html(html_path, font_path))
            for font_path in preload_paths
        ]
        local_links.append(LOCAL_LINK_MARKER.format(path=rel_from_html(html_path, FONT_CSS)))
        insertion = "\n".join(local_links)

        if html_path.parent == ROOT:
            main_link = '<link href="css/main.css" rel="stylesheet"/>'
        else:
            main_link = '<link href="../css/main.css" rel="stylesheet"/>'
        if main_link not in html:
            raise SystemExit(f"Could not find main stylesheet link in {html_path.relative_to(ROOT)}")
        html = html.replace(main_link, insertion + "\n" + main_link)
        html_path.write_text(html, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true", help="Fetch fresh Google font files and update the manifest.")
    args = parser.parse_args(argv)

    if MANIFEST.exists() and not args.refresh:
        manifest = load_manifest()
        verify_manifest(manifest)
        activate_local_fonts(manifest)
        print("Verified locked local Lora fonts and activated local font links.")
        return 0

    if MANIFEST.exists() and args.refresh and os.environ.get("ALLOW_FONT_UPDATE") != "1":
        raise SystemExit("Refusing to refresh locked fonts without ALLOW_FONT_UPDATE=1.")

    try:
        remove_old_generated_fonts()
        manifest = download_and_rewrite_css()
        verify_manifest(manifest)
        activate_local_fonts(manifest)
    except Exception as exc:
        raise SystemExit(f"Font fetch failed: {exc}") from exc

    print(f"Fetched and locked {len(manifest.get('fonts', []))} Google Lora font files.")
    print("Updated HTML to use css/local-fonts.css and removed Google Fonts runtime links.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
