#!/usr/bin/env python3
"""Fetch and activate the exact Lora webfonts used by the original site.

This deliberately does *not* use Fontsource. The prior Fontsource package used
Lora font binaries that were not identical to the Google Fonts version the site
had been rendering with, which changed the settled appearance. Instead, this
script asks Google Fonts for the same CSS request that the original HTML used,
downloads the WOFF2 files referenced by that CSS, rewrites those URLs to local
paths, and updates the HTML to remove runtime Google Fonts requests.
"""
from __future__ import annotations

import hashlib
import re
import sys
import urllib.request
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "fonts" / "lora"
FONT_CSS = ROOT / "css" / "local-fonts.css"
GOOGLE_CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Lora:ital,wght@0,400..700;1,400..700&display=block"
)
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/149.0.0.0 Safari/537.36"
)

URL_RE = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")
GOOGLE_LINK_RE = re.compile(
    r'\n?<link[^>]+(?:fonts\.googleapis\.com|fonts\.gstatic\.com)[^>]*>',
    flags=re.IGNORECASE,
)
LOCAL_LINK_MARKER = '<link href="{path}" rel="stylesheet" data-local-fonts="lora"/>'
PRELOAD_MARKER = (
    '<link href="{path}" rel="preload" as="font" type="font/woff2" crossorigin data-local-font="lora"/>'
)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def rel_from_html(html_path: Path, target: Path) -> str:
    # These files are one level deep at most; keep paths simple and POSIX.
    rel = target.relative_to(ROOT)
    if html_path.parent == ROOT:
        return rel.as_posix()
    return (Path("..") / rel).as_posix()


def normalize_css(css: str) -> tuple[str, list[Path]]:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    downloaded: list[Path] = []

    def replace_url(match: re.Match[str]) -> str:
        url = match.group(1)
        data = fetch(url)
        digest = hashlib.sha256(data).hexdigest()[:12]
        basename = Path(urlparse(url).path).name or "lora.woff2"
        # Google URLs are opaque; the digest keeps names stable and collision-safe.
        filename = f"lora-google-{digest}-{basename}"
        target = FONT_DIR / filename
        target.write_bytes(data)
        downloaded.append(target)
        return f"url('../fonts/lora/{filename}')"

    rewritten = URL_RE.sub(replace_url, css)
    if not downloaded:
        raise SystemExit("Google Fonts CSS was fetched, but no fonts.gstatic.com URLs were found.")
    banner = (
        "/* Generated by scripts/fetch_fonts.py. Do not hand-edit.\n"
        "   Source: the original Google Fonts CSS request for Lora. */\n"
    )
    return banner + rewritten, downloaded


def choose_preload_fonts(downloaded: list[Path]) -> list[Path]:
    """Preload only the likely first-paint Latin normal/italic faces.

    Google Fonts may return many unicode-range shards. Preloading the first two
    files blindly can waste requests on non-Latin subsets. The generated file
    names are opaque, so we infer from the generated CSS blocks after download.
    If that structure changes, falling back to the first two keeps the script
    conservative rather than failing.
    """
    css_path = FONT_CSS
    if not css_path.exists():
        return downloaded[:2]

    # This helper is normally called before FONT_CSS is written, so the caller
    # sets _last_generated_css when available. Keep a disk fallback for
    # idempotent external use.
    css = globals().get("_last_generated_css")
    if not isinstance(css, str):
        css = css_path.read_text(encoding="utf-8")

    chosen: list[Path] = []
    for style in ("normal", "italic"):
        for font_path in downloaded:
            name = re.escape(font_path.name)
            block_re = re.compile(
                r"@font-face\s*{[^}]*font-style:\s*" + style +
                r";[^}]*" + name + r"[^}]*unicode-range:\s*[^;}]*U\+0000-00FF",
                flags=re.IGNORECASE | re.DOTALL,
            )
            if block_re.search(css):
                chosen.append(font_path)
                break

    return chosen or downloaded[:2]


def update_html(downloaded: list[Path]) -> None:
    html_files = [ROOT / "index.html", *sorted((ROOT / "pages").glob("*.html"))]
    for html_path in html_files:
        html = html_path.read_text(encoding="utf-8")

        # Remove old Google runtime font requests and any previous local generated links.
        html = GOOGLE_LINK_RE.sub("", html)
        html = re.sub(r'\n?<link[^>]+data-local-fonts="lora"[^>]*>', "", html)
        html = re.sub(r'\n?<link[^>]+data-local-font="lora"[^>]*>', "", html)

        css_href = rel_from_html(html_path, FONT_CSS)
        preload_paths = choose_preload_fonts(downloaded)
        local_links = [
            PRELOAD_MARKER.format(path=rel_from_html(html_path, font_path))
            for font_path in preload_paths
        ]
        local_links.append(LOCAL_LINK_MARKER.format(path=css_href))
        insertion = "\n".join(local_links)

        # Put local font CSS before the main site CSS.
        html = html.replace('<link href="css/main.css" rel="stylesheet"/>', insertion + '\n<link href="css/main.css" rel="stylesheet"/>')
        html = html.replace('<link href="../css/main.css" rel="stylesheet"/>', insertion + '\n<link href="../css/main.css" rel="stylesheet"/>')
        html_path.write_text(html, encoding="utf-8")


def main() -> None:
    try:
        css = fetch(GOOGLE_CSS_URL).decode("utf-8")
        rewritten_css, downloaded = normalize_css(css)
    except Exception as exc:
        raise SystemExit(f"Font fetch failed: {exc}") from exc

    globals()["_last_generated_css"] = rewritten_css
    FONT_CSS.write_text(rewritten_css, encoding="utf-8")
    (FONT_DIR / "SOURCE.txt").write_text(
        "Generated by make fonts.\n"
        f"CSS source: {GOOGLE_CSS_URL}\n"
        f"User-Agent: {USER_AGENT}\n"
        "The generated CSS is css/local-fonts.css.\n",
        encoding="utf-8",
    )
    update_html(downloaded)
    print(f"Fetched {len(downloaded)} Google Lora font files into {FONT_DIR.relative_to(ROOT)}")
    print("Updated HTML to use css/local-fonts.css and removed Google Fonts runtime links.")


if __name__ == "__main__":
    main()
